# Generated by Django 2.1.7 on 2019-04-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=300, unique=True)),
                ('rg', models.CharField(max_length=60, unique=True)),
                ('cpf', models.CharField(max_length=80, unique=True)),
                ('celular', models.CharField(max_length=80)),
                ('telefone', models.CharField(blank=True, max_length=80)),
                ('estado', models.CharField(max_length=300)),
                ('cidade', models.CharField(max_length=300)),
                ('sangue', models.CharField(blank=True, max_length=300)),
                ('endereco', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
